apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3s-server-landing

resources:
  - k8s/namespace.yaml
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/ingress.yaml

configMapGenerator:
  - name: landing-site
    files:
      - index.html=site/index.html
      - styles.css=site/styles.css
      - favicon.svg=site/favicon.svg

labels:
  - pairs:
      app.kubernetes.io/name: k3s-server-landing
      app.kubernetes.io/part-of: home-k3s
